name: Check system state

on:
  schedule:
    - cron: "0 0 1 */3 *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  check-system-state:
    name: Check system state
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Create output directory
        run: mkdir -p system-info

      - name: PostgreSQL packages list
        run: |
          dpkg -l | grep postgres > system-info/postgres-packages.txt || echo "No PostgreSQL packages found" > system-info/postgres-packages.txt

      - name: PostgreSQL package details
        run: |
          echo "PostgreSQL package details:" > system-info/postgres-details.txt
          dpkg-query -l | grep postgres >> system-info/postgres-details.txt || echo "No detailed package info" >> system-info/postgres-details.txt

      - name: Node.js version
        run: |
          node -v > system-info/node-version.txt || echo "Node.js not found" > system-info/node-version.txt

      - name: Python version
        run: |
          python3 --version > system-info/python-version.txt || echo "Python 3 not found" > system-info/python-version.txt

      - name: Configure git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit and push info files
        run: |
          git add system-info/
          git commit --allow-empty -m "update system info $(date '+%Y-%m-%d %H:%M:%S')"
          git push