name: "v2: Update counts"

on:
  workflow_dispatch:
  workflow_run:
    workflows:
      - "v2: Export vc table (Yesterday)" # ! non-test repo: "v2: Export table (Yesterday)"
    types:
      - completed

permissions:
  contents: write

jobs:
  update-counts:
    runs-on: ubuntu-latest
    env:
      REPO_NAME: ${{ secrets.REPO_NAME }}
      REPO_DIR: repo # temp

      REMOTE: https://x-access-token:${{ secrets.PUSH_TOKEN }}@github.com/arnottferels/${{ secrets.REPO_NAME }}.git
      REMOTE_BRANCH: main

      REMOTE_COUNT_FILE: build/${{ secrets.TABLE_NAME_VC }}/public/counts.json

      TABLE_NAME: ${{ secrets.TABLE_NAME_VC }} # ! non-test repo: "secrets.TABLE_NAME"

      SILENT: "1"
      OUTPUT_DIR: vc/v2/json # ! non-test repo: v2/json
      OUTPUT_COUNT_FILE: c.json

    steps:
      - uses: actions/checkout@v4.2.2

      - name: Clone target repo
        run: |
          git clone "$REMOTE" "$REPO_DIR"
          cd "$REPO_DIR"
          git checkout "$REMOTE_BRANCH"

      - uses: actions/setup-node@v4

      - name: Install and build
        run: |
          cd "$REPO_DIR"
          npm install
          npm run ${{ secrets.TABLE_NAME_VC }}:build

      - name: Commit to target repo
        run: |
          cd $REPO_DIR
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -q -m "${{ secrets.TABLE_NAME_VC }}(v2): Update build directory $(date -u +'%F %H:%M')" || echo "no changes"
          git push origin $REMOTE_BRANCH

      - name: Copy count file from target repo
        run: |
          mkdir -p "$OUTPUT_DIR"
          cp "$REPO_DIR/$REMOTE_COUNT_FILE" "$OUTPUT_DIR/$OUTPUT_COUNT_FILE"

      - name: Commit and push updated files
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          git stash -q --include-untracked
          git pull -q --rebase origin main || exit 1
          git stash pop -q

          git add "$OUTPUT_DIR"
          git commit -m "v2: Update $OUTPUT_DIR directory $(date -u +'%F %H:%M')" -q || echo "no changes"
          git push -q origin main
